### ISSUE TITLE
lol why is there more ae than Ae?

### ISSUE THREAD

**Issue by dxvv-software** [skywarspro15/TranchSoftwareSite#1]
@skywarspro15 Ae

**Comment by skywarspro15** [comment]
real

**Comment by datkat21** [comment]
yes

**Comment by skywarspro15** [comment]
OMg real

**Comment by datkat21** [comment]
yes real

**Comment by skywarspro15** [comment]
***Ae***
```vb
Ae
```

**Comment by skywarspro15** [comment]
```````````````````````

**Comment by skywarspro15** [comment]
- [x] Ae
- [x] Ae
- [x] Ae
- [x] Ae
- [x] Ae

**Comment by datkat21** [comment]
> * [ ]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae

AgrAeed

**Comment by datkat21** [comment]
Now that we have completed all the tasks, Ae 1-5, this issue should be marked as Ae.

**Comment by skywarspro15** [comment]
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae

**Comment by datkat21** [comment]
### heading

****

> * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae
> 
>     * [x]  Ae

oh no more issues???

**Comment by datkat21** [comment]
# Ae
![Ae](https://cdn.discordapp.com/emojis/973452942554333186.webp?size=48)

**Comment by skywarspro15** [comment]
- [ ] Ae
- [ ] - [ ] Ae
- [ ] - [ ] Ae
- [ ] - [ ] Ae
- [ ] - [ ] Ae
- [ ] - [ ] Ae
- [ ] - [ ] Ae
- [ ] - [ ] Ae
- [ ] - [ ] Ae

**Comment by skywarspro15** [comment]
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ] Ae
- [ ]

**Comment by dxvv-software** [comment]
OMG HOW MANY Ae! ![](https://camo.githubusercontent.com/673097eb9965aec6ddaee0d8aef29db271aa581a6b3b2e30e0fe494a01b761e3/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3937333435323934323535343333333138362e776562703f73697a653d3438)

**Comment by skywarspro15** [comment]
Yes

**Comment by dxvv-software** [comment]
> Yes

`o.o`
